version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:current
        auth:
          username: ppavlov
          password: $DOCKERHUB_PASSWORD
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t blockwizard .
  test:
    docker:
      - image: cimg/deploy:2023.01
        auth:
          username: ppavlov
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker run -it -d -p 16000:16000 -e "mode=broker" blockwizard
          docker run -it -d -p 16001:16001 -e "mode=node1" blockwizard
          docker run -it -d -p 16001:16001 -e "mode=node1" blockwizard
  push:
    docker:
      - image: cimg/deploy:2023.01
        auth:
          username: ppavlov
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run: docker tag blockwizard ppavlov/blockwizard
             docker push ppavlov/blockwizard
             
workflows:
  build_and_test:
    jobs:
      - build
      - test
