version: 2.1

# Define the jobs we want to run for this project
jobs:
  prepare-dependencies:
    docker:
      - image: cimg/base:current
        auth:
          username: ppavlov
          password: $DOCKERHUB_PASSWORD
     steps:
       - checkout
       - run:
          name: Compute version number
          command: echo "0.0.${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1:0:7}" | tee version.txt
       - persist_to_workspace:
          root: .
          paths:
              - .           
  build:
    environment:
      IMAGE_NAME: ppavlov/blockwizard
    docker:
      - image: cimg/base:current
        auth:
          username: ppavlov
          password: $DOCKERHUB_PASSWORD
    resource_class: medium
    steps:
      - attach_workspace:
           at: .  
      - checkout
      - setup_remote_docker
      - run:
         name: Production build
         command: |
            export __BUILD_VERSION="$(cat version.txt)"        
      - run: 
         name: Build Docker Image
         command: |
            docker build -t $IMAGE_NAME:latest .
      - persist_to_workspace:
         root: .
         paths:
             - .             
  test:
    environment:
      IMAGE_NAME: ppavlov/blockwizard
    docker:
      - image: cimg/deploy:2023.01
        auth:
          username: ppavlov
          password: $DOCKERHUB_PASSWORD
    resource_class: medium      
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run: |
          docker run -it -d -p 16000:16000 -e "mode=broker" $IMAGE_NAME:latest
          docker run -it -d -p 16001:16001 -e "mode=node1" $IMAGE_NAME:latest
          docker run -it -d -p 16001:16001 -e "mode=node1" $IMAGE_NAME:latest
  push:
    docker:
      - image: cimg/deploy:2023.01
        auth:
          username: ppavlov
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run: docker tag blockwizard ppavlov/blockwizard
             docker push ppavlov/blockwizard
             
workflows:
  build_and_test:
    jobs:
      - build
      - test
