version: 2.1

orbs:
    docker: circleci/docker@1.0.1
jobs:
  prepare-dependencies:
    docker:
      - image: cimg/base:current
        auth:
          username: ppavlov
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
         name: Compute version number
         command: echo "0.0.${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1:0:7}" | tee version.txt
      - persist_to_workspace:
         root: .
         paths:
             - .           
  build-production:
    docker:
      - image: cimg/base:current
        auth:
          username: ppavlov
          password: $DOCKERHUB_PASSWORD
    resource_class: medium
    steps:
      - attach_workspace:
           at: .  
      - run:
         name: Production build
         command: |
            export __BUILD_VERSION="$(cat version.txt)"        
      - persist_to_workspace:
         root: .
         paths:
             - .
  build-docker-image:
    machine:
            # The image uses the current tag, which always points to the most recent
            # supported release. If stability and determinism are crucial for your CI
            # pipeline, use a release date tag with your image, e.g. ubuntu-2004:202201-02
        image: ubuntu-2004:current
    steps:
        - attach_workspace:
             at: .
        - run:
           name: Setup __BUILD_VERSION envvar
           command: |
              echo 'export __BUILD_VERSION="$(cat version.txt)"' >> "$BASH_ENV"
        - docker/check:
              registry: $DOCKER_REGISTRY
        - docker/build:
              image: $DOCKER_IMAGE_NAME
              tag: $__BUILD_VERSION
              registry: $DOCKER_REGISTRY
        - docker/push:
              image: $DOCKER_IMAGE_NAME
              tag: $__BUILD_VERSION
              registry: $DOCKER_REGISTRY             
  test:
    environment:
      IMAGE_NAME: ppavlov/blockwizard
    docker:
      - image: cimg/deploy:2023.01
        auth:
          username: ppavlov
          password: $DOCKERHUB_PASSWORD
    resource_class: medium
    parallelism: 2
    steps:
        - attach_workspace:
             at: .
        - run: |
            docker run -it -d -p 16000:16000 -e "mode=broker" $IMAGE_NAME:latest
            docker run -it -d -p 16001:16001 -e "mode=node1" $IMAGE_NAME:latest
            docker run -it -d -p 16001:16001 -e "mode=node1" $IMAGE_NAME:latest
        - store_artifacts:
              path: test-results
        - store_test_results:
              path: test-results            
  deploy-docker-image:
      machine:
          image: ubuntu-2004:current
      steps:
          - attach_workspace:
                at: .
          - run:
              name: Setup __BUILD_VERSION envvar
              command: |
                  echo 'export __BUILD_VERSION="$(cat version.txt)"' >> "$BASH_ENV"
          - docker/check:
                registry: $DOCKER_REGISTRY
          - docker/pull:
                images: $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$__BUILD_VERSION
          - run:
              name: Tag the image as latest
              command: docker tag $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$__BUILD_VERSION $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:latest
          - docker/push:
                image: $DOCKER_IMAGE_NAME
                tag: latest
                registry: $DOCKER_REGISTRY
workflows:             
    version: 2
    build-test-deploy:
        jobs:
            - prepare-dependencies
            - build-production:
                  requires:
                      - prepare-dependencies
            - build-docker-image:
                  context: docker-hub
                  requires:
                      - build-production
            - deploy-docker-image:
                  context: docker-hub
                  requires:
                      - build-docker-image
            - test:
                  requires:
                      - deploy-docker-image
