version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    environment:
      IMAGE_NAME: ppavlov/blockwizard
    docker:
      - image: cimg/base:current
        auth:
          username: ppavlov
          password: $DOCKERHUB_PASSWORD
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker
      - run: 
         name: Build Docker Image
         command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            IMAGE_TAG=${CIRCLE_TAG/v/''}
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$IMAGE_TAG      
  test:
    docker:
      - image: cimg/deploy:2023.01
        auth:
          username: ppavlov
          password: $DOCKERHUB_PASSWORD
    resource_class: medium      
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker run -it -d -p 16000:16000 -e "mode=broker" $IMAGE_NAME
          docker run -it -d -p 16001:16001 -e "mode=node1" $IMAGE_NAME
          docker run -it -d -p 16001:16001 -e "mode=node1" $IMAGE_NAME
  push:
    docker:
      - image: cimg/deploy:2023.01
        auth:
          username: ppavlov
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run: docker tag blockwizard ppavlov/blockwizard
             docker push ppavlov/blockwizard
             
workflows:
  build_and_test:
    jobs:
      - build
      - test
