---
- name: creating the vpc
  ec2_vpc_net:
    name: "{{ app_name }}"
    cidr_block: 10.0.2.0/24
    region: "{{ region }}"
    dns_hostnames: yes
    dns_support: yes
    multi_ok: no
    tenancy: default
    tags:
      module: ec2_vpc_net
      Environment: blockwizard
      Contact: ppavlov
  register: vpc

- set_fact:
    id: "{{ vpc.vpc.id }}"

- name: creating the igw
  ec2_vpc_igw:
    vpc_id: "{{ id }}"
    state: present
    tags:
      Environment: blockwizard
      Name: "{{ app_name }}-igw"
  register: igw

- name: create admin access security group
  ec2_group:
    name: admin_access
    description: SSH access
    region: "{{ region }}"
    vpc_id: "{{ id }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
  tags: security_groups
  register: admin_access_group

- name: create broker and node security group
  ec2_group:
    name: "{{ app_name }}"
    description: "{{ app_name }} web access"
    region: "{{ region }}"
    rules:
      - proto: tcp
        from_port: 16000
        to_port: 16000
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 16001
        to_port: 16001
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 16002
        to_port: 16002
        cidr_ip: 0.0.0.0/0
    vpc_id: "{{ vpc.vpc_id }}"
  tags: security_groups
  register: app_security_group

- name: launch load balancer
  ec2_elb_lb:
    name: "{{ lb_name }}"
    region: "{{ region }}"
    state: present
    subnets: "{{ asg_subnets }}"
    connection_draining_timeout: 60
    security_group_ids: "{{ app_security_group.group_id }}"
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
    health_check:
        ping_protocol: tcp
        ping_port: 16001
        ping_path: "/"
        response_timeout: 5 
        interval: 30
        unhealthy_threshold: 3
        healthy_threshold: 3
  register: load_balancer
