---

- name: docker is installed
  yum:
    name: docker
    state: present

- name: pip is installed
  yum:
    name: python-pip
    state: present

- pip:
    name: docker-py
    executable: pip
    state: latest

- name: Make sure docker is running
  systemd:
    state: started
    name: docker
