---

- name: docker ind pips installed
  yum:
    name:
     - docker
     - python-pip
    state: present

- pip:
    name: docker-py
    executable: pip
    state: latest


- name: Make sure docker is running
  systemd:
    name: 'docker.service'
    daemon_reload: true
    enabled: "{{ service_enabled }}"
    masked: "{{ service_masked }}"
    state: "{{ service_state }}"
  register: enable_docker

- name: downloading docker-compose...
  become: yes
  become_user: root
  get_url:
    url: '{{ docker_compose_url }}/{{ docker_compose_ver }}/docker-compose-{{ docker_compose_platform }}'
    dest: '{{ docker_compose_install_dir }}/{{ docker_compose_install }}'
    mode: 0755

- name: link /usr/local/bin/docker-compose
  become: yes
  become_user: root
  file:
    src: '{{ docker_compose_install_dir }}/{{ docker_compose_install }}'
    dest: '{{ docker_compose_install_dir }}/docker-compose'
    state: link

- name: install bash completions...
  become: yes
  become_user: root
  get_url:
    url: https://raw.githubusercontent.com/docker/compose/master/contrib/completion/bash/docker-compose
    dest: '{{ docker_compose_bash_completion_d }}/docker-compose.sh'
    mode: 0644

